### ISSUE TITLE
Payload encryption (JWE)

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-masvs#133]
Payload encryption is something that has often risen within the security community as an addition to TLS based controls. We tried to keep it out for a long time. But it did come back in, for instance, financial sectors. Can we position it at the MASVS or at least talk about it, and explain which standards can be used at the MSTG?

**Comment by sushi2k** [comment]
According to my experience, payload encryption is something that usually gives a wrong sense of security to developers. Usually, the conversations that I had was: "How can you find a XSS/SQL Injection/XXE, it's all encrypted?"
Additionally, I can see many projects that are struggling very hard implementing it. 
If you do TLS correctly (version 1.3, secure ciphers etc.) and do SSL Pinning on top of that you apply the latest best practices available and the effort is manageable. Adding E2E Encryption gives you not really much more protection (encrypting sth that is already encrypted) but makes the implementation much more complicated. The only use case I see for E2E encryption is to additionally encrypt passwords and pins so that if a request is processed by a TLS termination proxy and sending the request unencrypted to another server in the DMZ. In this scenario sensitive information is still protected. 
I would still see it like this that the MASVS gives you guidance on requirements you should think about when implementing a mobile app that communicates with an API endpoint. And this list of requirements is the baseline, but it will not be complete as you might have additional requirements through regulations and this is where you need to add those requirements (like E2E encryption). 
But maybe we should write a paragraph about this topic, but not add it as a requirement itself. 
What do you think?

**Comment by commjoen** [comment]
Maybe we can have a requirement with an explanation? It can be sensible to put it more straightforward and focus on encrypting very sensitive info as an R-category requirement?

**Comment by commjoen** [comment]
Meeting notes:

Category: Impede Traffic interception

8.13 | MSTG‑RESILIENCE‑13 | As a defense in depth, next to having solid hardening of the communicating parties, application level payload encryption can be applied to further impede eavesdropping. | ✓ |

- Note the MSTG should explain what needs to happen: at least protecting the integrity and confidentiality (e.g. eith erhave shared keys and AES GCM, or use something like JWE and further explain it, depending on the processing power involved, etc..

**Comment by commjoen** [comment]
Fixed in #317

**Comment by Malikrehman00107** [comment]
@commjoen  so what was finalised ?

**Comment by cpholguera** [comment]
@Malikrehman00107 this issue is closed and outdated. This topic is going to be covered as part of

https://mas.owasp.org/MASWE/MASVS-RESILIENCE/MASWE-0096/
