### ISSUE TITLE
Fix the Spanish translation

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-masvs#265]
The Spanish translation is not accurate and should be fixed.

- update the translation of the MASVS
- update the Spanish excel
- make sure that all links are up to date given the new structure of the MSTG (use the english version as a base document)

**Comment by commjoen** [comment]
Thanks! Can you have a look at it please :) ?

**Comment by cpholguera** [comment]
I guess we'll better do this after the next release, right?

**Comment by commjoen** [comment]
sure, when the english version is done (e.g. pre-release of the MASVS is done), then we can start translating.

**Comment by commjoen** [comment]
It would be awesome if you could help us once more! We believe that this version of the translation will be much more stable 😉 In order to make sure it becomes easy: please add the following line in your translation, translated to your language:
`- Updated the MASVS in the following languages: Chinese (ZHTW), English, German, French, Russian, Spanish, and Japanese).`
This way we can simplify the translation process (e.g.: add the line to your changelog when you are done, so that you don’t have to update the translation again 😉 )

**Comment by martinmarsicano** [comment]
Tomorrow I will start this with some Uruguay Chapter college's.

**Comment by commjoen** [comment]
Fixed in #325
