### ISSUE TITLE
Discussion for MSTG‑AUTH‑12 (IP & device info for authentication)

### ISSUE THREAD

**Issue by TheDauntless** [OWASP/owasp-masvs#275]
In #274 the following control is added:

> | **4.12** | MSTG‑AUTH‑12 | Contextual information (IP, device etc.) should be considered as an additional factor of authentication for specific sensitive functionalities. In case of detected anomalies the user should re-authenticate. |  | ✓ |

This was suggested in #189 .

I think this is a dangerous thing to say, as we shouldn't tie IP and device info to authentication stuff. I do think that IP & device info can be part of device binding (chapter RE), and that it can be used to set up a stronger authentication attempt.

If you want to keep monitoring those in some way, that's a fraud detection mechanism of sorts and it's the same as detecting a sudden change of an IP address for any session for a normal web application. In that sense, I would think that there would be ASVS controls to back this up, but I wasn't able to find them.

**Comment by sushi2k** [comment]
Great idea! Putting it into authentication can really become misleading and even dangerous as all of these information can be spoofed easily. So shall we make a 2nd device binding requirement instead?

### Device Binding

| # | MSTG-ID | Description | R |
| --- | --- | --- | -- |
| **8.10** | MSTG‑RESILIENCE‑10 | The app implements a 'device binding' functionality using a device fingerprint derived from multiple properties unique to the device. | ✓ |
| **8.11** | MSTG‑RESILIENCE‑11 | Contextual information (IP, location etc.) should be considered as an additional factor for device binding. In case of detected anomalies the user should re-authenticate. | ✓ |

**Comment by A-AFTAHI** [comment]
We can do this. just as a remark adding a 8.11 in device binding we'll cause shifting of the next two requirements of V8.

**Comment by TheDauntless** [comment]
My 2c: Device binding means an app can only be run on a specific device, but shouldn't say anything about where that device is, since those things are circumstantial and can obviously change. Device binding (to me) is already an additional factor on top of the authentication without which you wouldn't even be able to log in. So saying that you have to "log in if this extra device binding fails" doesn't make sense in that regard. In Belgium, device binding is set up through an external second factor (bank card + card reader) which is then converted to a token that stays on the device. The current description makes it seem that you use device binding as an automatic login, because, if it fails, you are sent back to the authentication screen.

I would therefore not call this device binding, but rather something anomaly detection. As such, I propose we change this to a control that explains how the device has many features that can be used to collect circumstantial information that can be used to monitor for suspicious behaviour.

**Comment by commjoen** [comment]
Device binding should indeed be about binding an app instance to a device. Like we have already formulated in the MSTG. This can be mixing in your instanceID or identifierforVendor with your auth logic. Maybe we should rephrase how we want to use the location/sensor data alltogether with more of a focus on fraud detection and perhaps keep it out of the requirements, but somewhere as in-depth control, similar to payload encryption? E.g.: if you are in deep trouble/want to make sure that you know who a user is, whether he behaves normally, then you can use this.

**Comment by A-AFTAHI** [comment]
At the begining we started from this requirements from the Mobile security project:
q - Consider restricting access to sensitive data based on contextual information such as location (e.g. wallet app not usable if GPS data shows phone is outside Europe, car key not usable unless within 100m of car etc...). 

The idea was to use contextual information to add some control over some specific functionalities of the App and not the Whole authentification thing or for fraud detection  as mentioned in the MSTG : https://github.com/OWASP/owasp-mstg/blob/4d9938a3d767f56387fb2586886664aab89419e6/Document/0x04e-Testing-Authentication-and-Session-Management.md#supplementary-authentication

When i rethink it i see that the requirement should be an other factor for session management (based on the contexual info for each session, different autorization can granted : data access, functionalities,etc.) rather than device binding.

I will think of reformulation the requirement and get back to you.

**Comment by commjoen** [comment]
Let's merge MSTG‑RESILIENCE‑13 and MSTG‑AUTH‑11:
| **4.11** | MSTG‑AUTH‑11 | The app informs the user of all sensitive activities with their account. Users are able view a list of devices and their locations. Based on that users should be able to block specific devices. |  | ✓ |

**Comment by commjoen** [comment]
Fixed in #285
