### ISSUE TITLE
How could this practice apply to React Native application

### ISSUE THREAD

**Issue by booker-dragon** [OWASP/owasp-masvs#293]
I am looking at apply this practice to my project which is built with React Native
Some of the items require to have some code checking is in native level (JAVA/Object C), I wonder how we can do the same to React Native

**Comment by commjoen** [comment]
Hi @booker-dragon ! Very good point! Unfortunately we cannot keep up with all the hybrid frameworks there are, which is why we chose to support native apps only. sorry about that!
However, nothing should be in your way to start a hybrid-collective!!! ^^ Can you contact us on slack please? Because we might be able to do something else in there :-).

**Comment by commjoen** [comment]
As discussed on slack: can you start filling in https://drive.google.com/file/d/1P5FZ_Bup5eSPOmkePZA8cIpKGOKvngkN/view?usp=sharing ?

**Comment by commjoen** [comment]
For people outside of owasp: you can view it with https://drive.google.com/file/d/1P5FZ_Bup5eSPOmkePZA8cIpKGOKvngkN/view?usp=sharing

**Comment by commjoen** [comment]
Interesting blog on the subject: https://br3akp0int.blogspot.com/2019/09/securing-react-native-apps.html

**Comment by commjoen** [comment]
Will close this issue and move on at https://github.com/OWASP/owasp-mstg/issues/1482
