### ISSUE TITLE
Create Chinese simplify version masvs

### ISSUE THREAD

**Issue by boblone19** [OWASP/owasp-masvs#340]

**Comment by commjoen** [comment]
In order to automatically generate the docs upon release, please don't forget the following steps:

- [ ] 1. Add a `generate_document_[LANG].sh` to the Tools folder
- [ ] 2. Update `gitbookandepubandpdf.sh` with the language referenced
- [ ] 3. Extend `Apply_Link_Check.sh` and `Apply_Linter_Check.sh`
- [ ] 4. Update `gendocs.sh` and `gendoclsLocal.sh` so you can test it locally and see if the markdown land links make sense for the new language. Use this to file issues or report to the translator if fixes are necessary. Please check for pagination as well when you run it so that at release time, you have a proper PDF immediately
- [ ] 5. Extend `../.travis.yml` to include the new language
- [ ] 6. Update `../LANGS.md` to include the new language
- [ ] 7. Extend the `../README.md` with the newly available language

**Comment by commjoen** [comment]
> In order to automatically generate the docs upon release, please don't forget the following steps:
> 
> * [ ]  1. Add a `generate_document_[LANG].sh` to the Tools folder
> * [ ]  2. Update `gitbookandepubandpdf.sh` with the language referenced
> * [ ]  3. Extend `Apply_Link_Check.sh` and `Apply_Linter_Check.sh`
> * [ ]  4. Update `gendocs.sh` and `gendoclsLocal.sh` so you can test it locally and see if the markdown land links make sense for the new language. Use this to file issues or report to the translator if fixes are necessary. Please check for pagination as well when you run it so that at release time, you have a proper PDF immediately
> * [ ]  5. Extend `../.travis.yml` to include the new language
> * [ ]  6. Update `../LANGS.md` to include the new language
> * [ ]  7. Extend the `../README.md` with the newly available language

This is no longer necessary. Currently the new language is build in to the new automated buidl system

**Comment by commjoen** [comment]
Is there any translation work open to be done? or can we close this issue?

**Comment by sushi2k** [comment]
Translation is all done. Closing this ticket
