### ISSUE TITLE
Insecure Communication Channels for Enrollment

### ISSUE THREAD

**Issue by b-mueller** [OWASP/owasp-masvs#48]
Level 2, V5.5: "Verify that the app doesn't rely on insecure communication channels (e.g email and SMS) for critical operations, such as enrollments and OTPs."

Seems a bit harsh. An app I'm currently testing uses a combination of email and SMS to authenticate the user once during enrollment (= one OTP sent via SMS, another OTP via email, both have to be entered correctly). IMHO definitely secure enough to warrant a L2 verification.

Can we soften this requirement somehow? Surely no app should rely solely on email OTP for 2FA, but there a scenario as described above should be acceptable?

**Comment by sushi2k** [comment]
The thing is SMS can be read by any App on an Android device if it has the rights for it (don't know how this is done on iOS in detail).  Would it make sense to rely here on GCM (Google Cloud Messaging) and iOS Push notifications instead? AFAIK this would at least ensure that only the App itself can read the message and it is encrypted in transit.
Otherwise a combination like you mentioned might still be ok. But I would say this also depends on how long the  OTP or enrolment token is valid. If it's a minute I  it's not an issue if it's a day or even longer that's definitely an issue.

**Comment by commjoen** [comment]
I was wondering whether we should not just split it? It could well be that having 2FA based on SMS is something one could be ok with on a l2 app for instance for certain scenarios. Because it might not be a bad idea to bind to somebody his/her mobile phone number in some cases.

**Comment by sushi2k** [comment]
That's a good idea. So shall we make a Level 2 requirement with 2FA either via Email and SMS for onboarding and when executing critical functions (e.g. bank transfer) and one for Level 3 that should have a combination of those mechanism or use a hardware token or  secure channel as GCM or Apple Push notifications?
