### ISSUE TITLE
Differentiate between whitebox and blackbox?

### ISSUE THREAD

**Issue by daMatz** [OWASP/owasp-masvs#489]
The MASVS clearly states, that it is tailored to "whitebox" tests, where all the information (or at least most of it) is available to the evaluator:

> The recommended way of verifying compliance of a mobile app with the MASVS is by performing an "open book" review [...]

What about black- / greybox tests?
Often only limited information is available to the evaluator, so would it make sense to categorize the test-cases, if they can be performed within a test scenario that doesn't provide source code?
Examples: Most of the test cases can be performed at least to a certain extend without source code (e.g. with dynamic testing).
Some require source code in my opinion (e.g. MSTG-STORAGE‑6, MSTG-PLATFORM-8, most of the MSTG-CODE tests, ...).

So the question is if it makes sense to extend some parts of the MASVS to those kind of tests?

**Comment by sushi2k** [comment]
Hi @daMatz. 
You are right many times it cannot be a "open book" review, due to various reasons. The test cases in the MSTG, that link to the MASVS requirements via the MSTG-ID are always categorized into a static and dynamic testing part. 
This means if you have a white-box test, great, then please check the static and dynamic part. If there is only the IPA/APK (black box test) then you can definitely execute the dynamic part and maybe still do some static analysis by decompiling. 

We clarified this also in the MSTG  a bit more in detail: https://mobile-security.gitbook.io/mobile-security-testing-guide/overview/0x04b-mobile-app-security-testing#principles-of-testing. 

> There you can also find this statement: "A white-box test is the way to go if the app hasn't been tested before."

I think this is also a bit of educating the client and showing the different testing options (Black/Grey/White) and what makes sense for them. 

Very rarely we made statements if dynamic testing is not applicable, but usually we tried to explain static and dynamic testing so the tester can choose the best option to verify the requirement. 
(see dynamic analysis here https://mobile-security.gitbook.io/mobile-security-testing-guide/android-testing-guide/0x05i-testing-code-quality-and-build-settings#dynamic-analysis)

**Comment by daMatz** [comment]
Hey @sushi2k,
thanks for the detailed answer.
You are right, the split into a static and a dynamic part is a good way to handle this.
I thought about some extra classification, but as you mentioned there are also scenarios in which by decompiling you could still perform static tests on the decompiled code.
