### ISSUE TITLE
3.10 - 3.11

### ISSUE THREAD

**Issue by b-mueller** [OWASP/owasp-masvs#53]
_V3.10: Verify that keying materials have been used such that forward secrecy is provided.  
V3.11: Verify that keying materials are newly generated for each session and stored at the server for non-repudiation instead of on the device._

should we be talking about "session keys" instead of "keying materials"?

3.10 - what does this entail, any examples?

3.11 - do we _require_ that session keys to be stored for non-repudiation? 

I think we should re-combine this into something like:
1. Verify that session keys are newly generated for each session - that's a no-brainer and should be a L1 requirement, if we want to include it.
2. Verify that forward secrecy is provided - not sure about what level that belongs on?

IMHO no need to mention that keys shouldn't be stored on the device, that's already handled by other requirements. Do we have something else to say about non-repudiation?

**Comment by commjoen** [comment]
regarding 3.10: you need to make sure that you use different keys per session (or at l3/l4) per critical action. This way, if an attacker tries to get the message history, he cannot because if he compromised one of the keys, he only knows about that specific part of the communication. Examples could be message encryption in chat-applications, or refreshed encryption at banking apps.

regarding 3.11: I think we should actually store the keys used for actions which require non-repudiation, such as the signing of a transaction at a banking application. Session keys by themselves might not have to be stored for non-repudiation if the application is speficially aimed at providing privacy.

maybe we can indeed make them like this:

3.10: Verify that session keys are newly generated for each session --> L1
3.11: Verify that forward secrecy is provided on an acceptable granular level. This can either be on message-basis or on a preset interval.  -->L3
3.12: Verify that keys public keys are stored at the server in case of signing actions to provide non-repudiation. --> L3

I have to say, it should be ok to store keys encrypted on a device to actually provide non-repudiation. If you would for instance store both the public and private key of a user on the same server, then you could not guarantee any of the signatures non-repudiation in case of a breach. However, if the server would only store the public key and have a storage key that protects the private key on the device, you have to compromise each device and the server to get rid of non-repudiation.

**Comment by jmanico** [comment]
"different keys per session"

If you use an ephemeral key exchange algorithm (perfect forward security) - which you should - then you get this automatically.

--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by b-mueller** [comment]
So are we talking only about apps that implement payload encryption or transaction signing on top of TLS? 
I still don't think it's a good idea overall to require developers implement their own encryption, key storage and so forth. It opens a huge can of worms. If we put this into the requirements, 90% of developers will produce a mess.
I understand that TLS offers ephemeral key exchange but not non-repudiation. However, in my view non-repudiation is a possible business requirement and not necessarily a technical requirement. If at all, I'd offer a control such as "If non-repudiation is required, verify that...".

**Comment by b-mueller** [comment]
OK I made the following changes:

+ 5.5	Verify that the secure communcation protocol used enables perfect forward secrecy.

Chapter 3:

3.2	Verify that the app uses proven implementations of cryptographic functions.	
3.3	Verify that the app does not use cryptographic protocols or algorithms that are widely considered depreciated.
3.3	Verify that cryptographic modules use parameters that adhere to current industry best practices. This includes key length and modes of operation.

"verify session keys are newly generated for each session" ->  covered automatically when proven implementations are used.

"Verify that keys public keys are stored at the server in case of signing actions to provide non-repudiation." -> covered implicitly by V2: do not store sensitive data on the device

**Comment by StefaanSeys** [comment]
3.11 I do not think we should talk about non-repudiation. That is a pure business requirement, not a standard technical security requirement. I would remove this requirement entirely.

(If we really want to say something about non-repudiation, I would put the requirement like this (perhaps remove ISO ref if it is against policy to put refs like that in).)
> If non-repudiation is a business requirement, it should be based on techniques that follow industry best practices (such as the ISO/IEC 13888 family of standards).

3.10 I would keep it as it is. Requiring forward secrecy is a L4 according to me.

**Comment by b-mueller** [comment]
Closing this, current ongoing discussion is taking place in #78
