### ISSUE TITLE
V2.1 - Secure Storage of Sensitive Data

### ISSUE THREAD

**Issue by b-mueller** [OWASP/owasp-masvs#9]
"2.1	Verify that secure credential storage facilities are used to store sensitive data, such as user credentials or cryptographic keys."

This is supposed to cover ALL sensitive data. The question is, do we also allow the use of other encryption methods besides the standard iOS Keychain and Android KeyStore APIs? Wouldn't any symmetric crypto have to rely on hardcoded keys, which is forbidden by V3.1?

**Comment by sushi2k** [comment]
I would definitely say yes, that other encryption methods should be allowed besides keychain. There might still be cases where storing data in a SQLite database might be more feasible, therefore usage of a library like SQLCipher to encrypt the database can also be applicable.
If something like SQLCipher is used the problem is of course where to store the key, that might be violating V3.1. But there can still be two solutions besides having a hardcoded key that would not violate V3.1:

- Store the key on the server and not locally and only retrieve the key when data needs to be decrypted. This has of course the downside that the App might mot be usable when being offline. 

- Ask the user for a PIN/Password that is part of the secret to decrypt the data. This might be prone to brute forcing if the PIN/Password is weak.

Besides that White Box cryptography controls can be applied for symmetric keys, which can be another requirement for cryptography that might be applicable to Level 3 or 4.

**Comment by b-mueller** [comment]
Ok, that makes sense. I like the part with the PIN requirement, and we also need minimum requirements for the PIN. Using something “the user knows” is really the only way to do it.

**Comment by b-mueller** [comment]
Closed together with issue #10.
